services:
  - type: web
    name: expenz-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: GEMINI_API_KEY
        sync: false
